/* Additional record code for Motoreducteur generated by the OpenModelica Compiler OpenModelica v1.21.0 (64-bit). */

#include "omc_simulation_settings.h"
#include "meta/meta_modelica.h"
#include "Motoreducteur_functions.h"

#ifdef __cplusplus
extern "C" {
#endif


#ifdef __cplusplus
}
#endif

