/* Additional record code for Modelica_Fluid_Examples_HeatingSystem generated by the OpenModelica Compiler OpenModelica v1.21.0 (64-bit). */

#include "omc_simulation_settings.h"
#include "meta/meta_modelica.h"
#include "Modelica_Fluid_Examples_HeatingSystem_functions.h"

#ifdef __cplusplus
extern "C" {
#endif

#define Modelica_Fluid_Examples_HeatingSystem_heater_Medium_ThermodynamicState__desc_added 1
const char* Modelica_Fluid_Examples_HeatingSystem_heater_Medium_ThermodynamicState__desc__fields[2] = {"p","T"};
struct record_description Modelica_Fluid_Examples_HeatingSystem_heater_Medium_ThermodynamicState__desc = {
  "Modelica_Fluid_Examples_HeatingSystem_heater_Medium_ThermodynamicState", /* package_record__X */
  "Modelica.Fluid.Examples.HeatingSystem.heater.Medium.ThermodynamicState", /* package.record_X */
  Modelica_Fluid_Examples_HeatingSystem_heater_Medium_ThermodynamicState__desc__fields
};

void Modelica_Fluid_Examples_HeatingSystem_heater_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths ) {
  Modelica_Fluid_Examples_HeatingSystem_heater_Medium_ThermodynamicState* ths = (Modelica_Fluid_Examples_HeatingSystem_heater_Medium_ThermodynamicState*)(v_ths);
  // ths->_p has no default value.
  // ths->_T has no default value.
}
void Modelica_Fluid_Examples_HeatingSystem_heater_Medium_ThermodynamicState_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_real in_p, modelica_real in_T) {
  Modelica_Fluid_Examples_HeatingSystem_heater_Medium_ThermodynamicState* dst = (Modelica_Fluid_Examples_HeatingSystem_heater_Medium_ThermodynamicState*)(v_dst);
  dst->_p = in_p;
  dst->_T = in_T;
}

void Modelica_Fluid_Examples_HeatingSystem_heater_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst) {
  Modelica_Fluid_Examples_HeatingSystem_heater_Medium_ThermodynamicState* src = (Modelica_Fluid_Examples_HeatingSystem_heater_Medium_ThermodynamicState*)(v_src);
  Modelica_Fluid_Examples_HeatingSystem_heater_Medium_ThermodynamicState* dst = (Modelica_Fluid_Examples_HeatingSystem_heater_Medium_ThermodynamicState*)(v_dst);
  dst->_p = src->_p;
  dst->_T = src->_T;
}


#define Modelica_Fluid_Examples_HeatingSystem_tank_Medium_SaturationProperties__desc_added 1
const char* Modelica_Fluid_Examples_HeatingSystem_tank_Medium_SaturationProperties__desc__fields[2] = {"psat","Tsat"};
struct record_description Modelica_Fluid_Examples_HeatingSystem_tank_Medium_SaturationProperties__desc = {
  "Modelica_Fluid_Examples_HeatingSystem_tank_Medium_SaturationProperties", /* package_record__X */
  "Modelica.Fluid.Examples.HeatingSystem.tank.Medium.SaturationProperties", /* package.record_X */
  Modelica_Fluid_Examples_HeatingSystem_tank_Medium_SaturationProperties__desc__fields
};

void Modelica_Fluid_Examples_HeatingSystem_tank_Medium_SaturationProperties_construct_p(threadData_t *threadData, void* v_ths ) {
  Modelica_Fluid_Examples_HeatingSystem_tank_Medium_SaturationProperties* ths = (Modelica_Fluid_Examples_HeatingSystem_tank_Medium_SaturationProperties*)(v_ths);
  // ths->_psat has no default value.
  // ths->_Tsat has no default value.
}
void Modelica_Fluid_Examples_HeatingSystem_tank_Medium_SaturationProperties_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_real in_psat, modelica_real in_Tsat) {
  Modelica_Fluid_Examples_HeatingSystem_tank_Medium_SaturationProperties* dst = (Modelica_Fluid_Examples_HeatingSystem_tank_Medium_SaturationProperties*)(v_dst);
  dst->_psat = in_psat;
  dst->_Tsat = in_Tsat;
}

void Modelica_Fluid_Examples_HeatingSystem_tank_Medium_SaturationProperties_copy_p(void* v_src, void* v_dst) {
  Modelica_Fluid_Examples_HeatingSystem_tank_Medium_SaturationProperties* src = (Modelica_Fluid_Examples_HeatingSystem_tank_Medium_SaturationProperties*)(v_src);
  Modelica_Fluid_Examples_HeatingSystem_tank_Medium_SaturationProperties* dst = (Modelica_Fluid_Examples_HeatingSystem_tank_Medium_SaturationProperties*)(v_dst);
  dst->_psat = src->_psat;
  dst->_Tsat = src->_Tsat;
}


#define Modelica_Fluid_Examples_HeatingSystem_tank_Medium_ThermodynamicState__desc_added 1
const char* Modelica_Fluid_Examples_HeatingSystem_tank_Medium_ThermodynamicState__desc__fields[5] = {"phase","h","d","T","p"};
struct record_description Modelica_Fluid_Examples_HeatingSystem_tank_Medium_ThermodynamicState__desc = {
  "Modelica_Fluid_Examples_HeatingSystem_tank_Medium_ThermodynamicState", /* package_record__X */
  "Modelica.Fluid.Examples.HeatingSystem.tank.Medium.ThermodynamicState", /* package.record_X */
  Modelica_Fluid_Examples_HeatingSystem_tank_Medium_ThermodynamicState__desc__fields
};

void Modelica_Fluid_Examples_HeatingSystem_tank_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths ) {
  Modelica_Fluid_Examples_HeatingSystem_tank_Medium_ThermodynamicState* ths = (Modelica_Fluid_Examples_HeatingSystem_tank_Medium_ThermodynamicState*)(v_ths);
  // ths->_phase has no default value.
  // ths->_h has no default value.
  // ths->_d has no default value.
  // ths->_T has no default value.
  // ths->_p has no default value.
}
void Modelica_Fluid_Examples_HeatingSystem_tank_Medium_ThermodynamicState_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_integer in_phase, modelica_real in_h, modelica_real in_d, modelica_real in_T, modelica_real in_p) {
  Modelica_Fluid_Examples_HeatingSystem_tank_Medium_ThermodynamicState* dst = (Modelica_Fluid_Examples_HeatingSystem_tank_Medium_ThermodynamicState*)(v_dst);
  dst->_phase = in_phase;
  dst->_h = in_h;
  dst->_d = in_d;
  dst->_T = in_T;
  dst->_p = in_p;
}

void Modelica_Fluid_Examples_HeatingSystem_tank_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst) {
  Modelica_Fluid_Examples_HeatingSystem_tank_Medium_ThermodynamicState* src = (Modelica_Fluid_Examples_HeatingSystem_tank_Medium_ThermodynamicState*)(v_src);
  Modelica_Fluid_Examples_HeatingSystem_tank_Medium_ThermodynamicState* dst = (Modelica_Fluid_Examples_HeatingSystem_tank_Medium_ThermodynamicState*)(v_dst);
  dst->_phase = src->_phase;
  dst->_h = src->_h;
  dst->_d = src->_d;
  dst->_T = src->_T;
  dst->_p = src->_p;
}


#define Modelica_Media_Common_GibbsDerivs__desc_added 1
const char* Modelica_Media_Common_GibbsDerivs__desc__fields[11] = {"p","T","R_s","pi","tau","g","gpi","gpipi","gtau","gtautau","gtaupi"};
struct record_description Modelica_Media_Common_GibbsDerivs__desc = {
  "Modelica_Media_Common_GibbsDerivs", /* package_record__X */
  "Modelica.Media.Common.GibbsDerivs", /* package.record_X */
  Modelica_Media_Common_GibbsDerivs__desc__fields
};

void Modelica_Media_Common_GibbsDerivs_construct_p(threadData_t *threadData, void* v_ths ) {
  Modelica_Media_Common_GibbsDerivs* ths = (Modelica_Media_Common_GibbsDerivs*)(v_ths);
  // ths->_p has no default value.
  // ths->_T has no default value.
  // ths->_R_s has no default value.
  // ths->_pi has no default value.
  // ths->_tau has no default value.
  // ths->_g has no default value.
  // ths->_gpi has no default value.
  // ths->_gpipi has no default value.
  // ths->_gtau has no default value.
  // ths->_gtautau has no default value.
  // ths->_gtaupi has no default value.
}
void Modelica_Media_Common_GibbsDerivs_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_real in_p, modelica_real in_T, modelica_real in_R_s, modelica_real in_pi, modelica_real in_tau, modelica_real in_g, modelica_real in_gpi, modelica_real in_gpipi, modelica_real in_gtau, modelica_real in_gtautau, modelica_real in_gtaupi) {
  Modelica_Media_Common_GibbsDerivs* dst = (Modelica_Media_Common_GibbsDerivs*)(v_dst);
  dst->_p = in_p;
  dst->_T = in_T;
  dst->_R_s = in_R_s;
  dst->_pi = in_pi;
  dst->_tau = in_tau;
  dst->_g = in_g;
  dst->_gpi = in_gpi;
  dst->_gpipi = in_gpipi;
  dst->_gtau = in_gtau;
  dst->_gtautau = in_gtautau;
  dst->_gtaupi = in_gtaupi;
}

void Modelica_Media_Common_GibbsDerivs_copy_p(void* v_src, void* v_dst) {
  Modelica_Media_Common_GibbsDerivs* src = (Modelica_Media_Common_GibbsDerivs*)(v_src);
  Modelica_Media_Common_GibbsDerivs* dst = (Modelica_Media_Common_GibbsDerivs*)(v_dst);
  dst->_p = src->_p;
  dst->_T = src->_T;
  dst->_R_s = src->_R_s;
  dst->_pi = src->_pi;
  dst->_tau = src->_tau;
  dst->_g = src->_g;
  dst->_gpi = src->_gpi;
  dst->_gpipi = src->_gpipi;
  dst->_gtau = src->_gtau;
  dst->_gtautau = src->_gtautau;
  dst->_gtaupi = src->_gtaupi;
}


#define Modelica_Media_Common_HelmholtzDerivs__desc_added 1
const char* Modelica_Media_Common_HelmholtzDerivs__desc__fields[11] = {"d","T","R_s","delta","tau","f","fdelta","fdeltadelta","ftau","ftautau","fdeltatau"};
struct record_description Modelica_Media_Common_HelmholtzDerivs__desc = {
  "Modelica_Media_Common_HelmholtzDerivs", /* package_record__X */
  "Modelica.Media.Common.HelmholtzDerivs", /* package.record_X */
  Modelica_Media_Common_HelmholtzDerivs__desc__fields
};

void Modelica_Media_Common_HelmholtzDerivs_construct_p(threadData_t *threadData, void* v_ths ) {
  Modelica_Media_Common_HelmholtzDerivs* ths = (Modelica_Media_Common_HelmholtzDerivs*)(v_ths);
  // ths->_d has no default value.
  // ths->_T has no default value.
  // ths->_R_s has no default value.
  // ths->_delta has no default value.
  // ths->_tau has no default value.
  // ths->_f has no default value.
  // ths->_fdelta has no default value.
  // ths->_fdeltadelta has no default value.
  // ths->_ftau has no default value.
  // ths->_ftautau has no default value.
  // ths->_fdeltatau has no default value.
}
void Modelica_Media_Common_HelmholtzDerivs_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_real in_d, modelica_real in_T, modelica_real in_R_s, modelica_real in_delta, modelica_real in_tau, modelica_real in_f, modelica_real in_fdelta, modelica_real in_fdeltadelta, modelica_real in_ftau, modelica_real in_ftautau, modelica_real in_fdeltatau) {
  Modelica_Media_Common_HelmholtzDerivs* dst = (Modelica_Media_Common_HelmholtzDerivs*)(v_dst);
  dst->_d = in_d;
  dst->_T = in_T;
  dst->_R_s = in_R_s;
  dst->_delta = in_delta;
  dst->_tau = in_tau;
  dst->_f = in_f;
  dst->_fdelta = in_fdelta;
  dst->_fdeltadelta = in_fdeltadelta;
  dst->_ftau = in_ftau;
  dst->_ftautau = in_ftautau;
  dst->_fdeltatau = in_fdeltatau;
}

void Modelica_Media_Common_HelmholtzDerivs_copy_p(void* v_src, void* v_dst) {
  Modelica_Media_Common_HelmholtzDerivs* src = (Modelica_Media_Common_HelmholtzDerivs*)(v_src);
  Modelica_Media_Common_HelmholtzDerivs* dst = (Modelica_Media_Common_HelmholtzDerivs*)(v_dst);
  dst->_d = src->_d;
  dst->_T = src->_T;
  dst->_R_s = src->_R_s;
  dst->_delta = src->_delta;
  dst->_tau = src->_tau;
  dst->_f = src->_f;
  dst->_fdelta = src->_fdelta;
  dst->_fdeltadelta = src->_fdeltadelta;
  dst->_ftau = src->_ftau;
  dst->_ftautau = src->_ftautau;
  dst->_fdeltatau = src->_fdeltatau;
}


#define Modelica_Media_Common_NewtonDerivatives__pT__desc_added 1
const char* Modelica_Media_Common_NewtonDerivatives__pT__desc__fields[2] = {"p","pd"};
struct record_description Modelica_Media_Common_NewtonDerivatives__pT__desc = {
  "Modelica_Media_Common_NewtonDerivatives__pT", /* package_record__X */
  "Modelica.Media.Common.NewtonDerivatives_pT", /* package.record_X */
  Modelica_Media_Common_NewtonDerivatives__pT__desc__fields
};

void Modelica_Media_Common_NewtonDerivatives__pT_construct_p(threadData_t *threadData, void* v_ths ) {
  Modelica_Media_Common_NewtonDerivatives__pT* ths = (Modelica_Media_Common_NewtonDerivatives__pT*)(v_ths);
  // ths->_p has no default value.
  // ths->_pd has no default value.
}
void Modelica_Media_Common_NewtonDerivatives__pT_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_real in_p, modelica_real in_pd) {
  Modelica_Media_Common_NewtonDerivatives__pT* dst = (Modelica_Media_Common_NewtonDerivatives__pT*)(v_dst);
  dst->_p = in_p;
  dst->_pd = in_pd;
}

void Modelica_Media_Common_NewtonDerivatives__pT_copy_p(void* v_src, void* v_dst) {
  Modelica_Media_Common_NewtonDerivatives__pT* src = (Modelica_Media_Common_NewtonDerivatives__pT*)(v_src);
  Modelica_Media_Common_NewtonDerivatives__pT* dst = (Modelica_Media_Common_NewtonDerivatives__pT*)(v_dst);
  dst->_p = src->_p;
  dst->_pd = src->_pd;
}


#define Modelica_Media_Common_NewtonDerivatives__ph__desc_added 1
const char* Modelica_Media_Common_NewtonDerivatives__ph__desc__fields[6] = {"p","h","pd","pt","hd","ht"};
struct record_description Modelica_Media_Common_NewtonDerivatives__ph__desc = {
  "Modelica_Media_Common_NewtonDerivatives__ph", /* package_record__X */
  "Modelica.Media.Common.NewtonDerivatives_ph", /* package.record_X */
  Modelica_Media_Common_NewtonDerivatives__ph__desc__fields
};

void Modelica_Media_Common_NewtonDerivatives__ph_construct_p(threadData_t *threadData, void* v_ths ) {
  Modelica_Media_Common_NewtonDerivatives__ph* ths = (Modelica_Media_Common_NewtonDerivatives__ph*)(v_ths);
  // ths->_p has no default value.
  // ths->_h has no default value.
  // ths->_pd has no default value.
  // ths->_pt has no default value.
  // ths->_hd has no default value.
  // ths->_ht has no default value.
}
void Modelica_Media_Common_NewtonDerivatives__ph_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_real in_p, modelica_real in_h, modelica_real in_pd, modelica_real in_pt, modelica_real in_hd, modelica_real in_ht) {
  Modelica_Media_Common_NewtonDerivatives__ph* dst = (Modelica_Media_Common_NewtonDerivatives__ph*)(v_dst);
  dst->_p = in_p;
  dst->_h = in_h;
  dst->_pd = in_pd;
  dst->_pt = in_pt;
  dst->_hd = in_hd;
  dst->_ht = in_ht;
}

void Modelica_Media_Common_NewtonDerivatives__ph_copy_p(void* v_src, void* v_dst) {
  Modelica_Media_Common_NewtonDerivatives__ph* src = (Modelica_Media_Common_NewtonDerivatives__ph*)(v_src);
  Modelica_Media_Common_NewtonDerivatives__ph* dst = (Modelica_Media_Common_NewtonDerivatives__ph*)(v_dst);
  dst->_p = src->_p;
  dst->_h = src->_h;
  dst->_pd = src->_pd;
  dst->_pt = src->_pt;
  dst->_hd = src->_hd;
  dst->_ht = src->_ht;
}


#define Modelica_Media_Common_IF97BaseTwoPhase__desc_added 1
const char* Modelica_Media_Common_IF97BaseTwoPhase__desc__fields[16] = {"phase","region","p","T","h","R_s","cp","cv","rho","s","pt","pd","vt","vp","x","dpT"};
struct record_description Modelica_Media_Common_IF97BaseTwoPhase__desc = {
  "Modelica_Media_Common_IF97BaseTwoPhase", /* package_record__X */
  "Modelica.Media.Common.IF97BaseTwoPhase", /* package.record_X */
  Modelica_Media_Common_IF97BaseTwoPhase__desc__fields
};

void Modelica_Media_Common_IF97BaseTwoPhase_construct_p(threadData_t *threadData, void* v_ths ) {
  Modelica_Media_Common_IF97BaseTwoPhase* ths = (Modelica_Media_Common_IF97BaseTwoPhase*)(v_ths);
  // ths->_phase has no default value.
  // ths->_region has no default value.
  // ths->_p has no default value.
  // ths->_T has no default value.
  // ths->_h has no default value.
  // ths->_R_s has no default value.
  // ths->_cp has no default value.
  // ths->_cv has no default value.
  // ths->_rho has no default value.
  // ths->_s has no default value.
  // ths->_pt has no default value.
  // ths->_pd has no default value.
  // ths->_vt has no default value.
  // ths->_vp has no default value.
  // ths->_x has no default value.
  // ths->_dpT has no default value.
}
void Modelica_Media_Common_IF97BaseTwoPhase_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_integer in_phase, modelica_integer in_region, modelica_real in_p, modelica_real in_T, modelica_real in_h, modelica_real in_R_s, modelica_real in_cp, modelica_real in_cv, modelica_real in_rho, modelica_real in_s, modelica_real in_pt, modelica_real in_pd, modelica_real in_vt, modelica_real in_vp, modelica_real in_x, modelica_real in_dpT) {
  Modelica_Media_Common_IF97BaseTwoPhase* dst = (Modelica_Media_Common_IF97BaseTwoPhase*)(v_dst);
  dst->_phase = in_phase;
  dst->_region = in_region;
  dst->_p = in_p;
  dst->_T = in_T;
  dst->_h = in_h;
  dst->_R_s = in_R_s;
  dst->_cp = in_cp;
  dst->_cv = in_cv;
  dst->_rho = in_rho;
  dst->_s = in_s;
  dst->_pt = in_pt;
  dst->_pd = in_pd;
  dst->_vt = in_vt;
  dst->_vp = in_vp;
  dst->_x = in_x;
  dst->_dpT = in_dpT;
}

void Modelica_Media_Common_IF97BaseTwoPhase_copy_p(void* v_src, void* v_dst) {
  Modelica_Media_Common_IF97BaseTwoPhase* src = (Modelica_Media_Common_IF97BaseTwoPhase*)(v_src);
  Modelica_Media_Common_IF97BaseTwoPhase* dst = (Modelica_Media_Common_IF97BaseTwoPhase*)(v_dst);
  dst->_phase = src->_phase;
  dst->_region = src->_region;
  dst->_p = src->_p;
  dst->_T = src->_T;
  dst->_h = src->_h;
  dst->_R_s = src->_R_s;
  dst->_cp = src->_cp;
  dst->_cv = src->_cv;
  dst->_rho = src->_rho;
  dst->_s = src->_s;
  dst->_pt = src->_pt;
  dst->_pd = src->_pd;
  dst->_vt = src->_vt;
  dst->_vp = src->_vp;
  dst->_x = src->_x;
  dst->_dpT = src->_dpT;
}


#define Modelica_Media_Common_IF97PhaseBoundaryProperties__desc_added 1
const char* Modelica_Media_Common_IF97PhaseBoundaryProperties__desc__fields[13] = {"region3boundary","R_s","T","d","h","s","cp","cv","dpT","pt","pd","vt","vp"};
struct record_description Modelica_Media_Common_IF97PhaseBoundaryProperties__desc = {
  "Modelica_Media_Common_IF97PhaseBoundaryProperties", /* package_record__X */
  "Modelica.Media.Common.IF97PhaseBoundaryProperties", /* package.record_X */
  Modelica_Media_Common_IF97PhaseBoundaryProperties__desc__fields
};

void Modelica_Media_Common_IF97PhaseBoundaryProperties_construct_p(threadData_t *threadData, void* v_ths ) {
  Modelica_Media_Common_IF97PhaseBoundaryProperties* ths = (Modelica_Media_Common_IF97PhaseBoundaryProperties*)(v_ths);
  // ths->_region3boundary has no default value.
  // ths->_R_s has no default value.
  // ths->_T has no default value.
  // ths->_d has no default value.
  // ths->_h has no default value.
  // ths->_s has no default value.
  // ths->_cp has no default value.
  // ths->_cv has no default value.
  // ths->_dpT has no default value.
  // ths->_pt has no default value.
  // ths->_pd has no default value.
  // ths->_vt has no default value.
  // ths->_vp has no default value.
}
void Modelica_Media_Common_IF97PhaseBoundaryProperties_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_boolean in_region3boundary, modelica_real in_R_s, modelica_real in_T, modelica_real in_d, modelica_real in_h, modelica_real in_s, modelica_real in_cp, modelica_real in_cv, modelica_real in_dpT, modelica_real in_pt, modelica_real in_pd, modelica_real in_vt, modelica_real in_vp) {
  Modelica_Media_Common_IF97PhaseBoundaryProperties* dst = (Modelica_Media_Common_IF97PhaseBoundaryProperties*)(v_dst);
  dst->_region3boundary = in_region3boundary;
  dst->_R_s = in_R_s;
  dst->_T = in_T;
  dst->_d = in_d;
  dst->_h = in_h;
  dst->_s = in_s;
  dst->_cp = in_cp;
  dst->_cv = in_cv;
  dst->_dpT = in_dpT;
  dst->_pt = in_pt;
  dst->_pd = in_pd;
  dst->_vt = in_vt;
  dst->_vp = in_vp;
}

void Modelica_Media_Common_IF97PhaseBoundaryProperties_copy_p(void* v_src, void* v_dst) {
  Modelica_Media_Common_IF97PhaseBoundaryProperties* src = (Modelica_Media_Common_IF97PhaseBoundaryProperties*)(v_src);
  Modelica_Media_Common_IF97PhaseBoundaryProperties* dst = (Modelica_Media_Common_IF97PhaseBoundaryProperties*)(v_dst);
  dst->_region3boundary = src->_region3boundary;
  dst->_R_s = src->_R_s;
  dst->_T = src->_T;
  dst->_d = src->_d;
  dst->_h = src->_h;
  dst->_s = src->_s;
  dst->_cp = src->_cp;
  dst->_cv = src->_cv;
  dst->_dpT = src->_dpT;
  dst->_pt = src->_pt;
  dst->_pd = src->_pd;
  dst->_vt = src->_vt;
  dst->_vp = src->_vp;
}


#define Modelica_Media_Common_PhaseBoundaryProperties__desc_added 1
const char* Modelica_Media_Common_PhaseBoundaryProperties__desc__fields[8] = {"d","h","u","s","cp","cv","pt","pd"};
struct record_description Modelica_Media_Common_PhaseBoundaryProperties__desc = {
  "Modelica_Media_Common_PhaseBoundaryProperties", /* package_record__X */
  "Modelica.Media.Common.PhaseBoundaryProperties", /* package.record_X */
  Modelica_Media_Common_PhaseBoundaryProperties__desc__fields
};

void Modelica_Media_Common_PhaseBoundaryProperties_construct_p(threadData_t *threadData, void* v_ths ) {
  Modelica_Media_Common_PhaseBoundaryProperties* ths = (Modelica_Media_Common_PhaseBoundaryProperties*)(v_ths);
  // ths->_d has no default value.
  // ths->_h has no default value.
  // ths->_u has no default value.
  // ths->_s has no default value.
  // ths->_cp has no default value.
  // ths->_cv has no default value.
  // ths->_pt has no default value.
  // ths->_pd has no default value.
}
void Modelica_Media_Common_PhaseBoundaryProperties_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_real in_d, modelica_real in_h, modelica_real in_u, modelica_real in_s, modelica_real in_cp, modelica_real in_cv, modelica_real in_pt, modelica_real in_pd) {
  Modelica_Media_Common_PhaseBoundaryProperties* dst = (Modelica_Media_Common_PhaseBoundaryProperties*)(v_dst);
  dst->_d = in_d;
  dst->_h = in_h;
  dst->_u = in_u;
  dst->_s = in_s;
  dst->_cp = in_cp;
  dst->_cv = in_cv;
  dst->_pt = in_pt;
  dst->_pd = in_pd;
}

void Modelica_Media_Common_PhaseBoundaryProperties_copy_p(void* v_src, void* v_dst) {
  Modelica_Media_Common_PhaseBoundaryProperties* src = (Modelica_Media_Common_PhaseBoundaryProperties*)(v_src);
  Modelica_Media_Common_PhaseBoundaryProperties* dst = (Modelica_Media_Common_PhaseBoundaryProperties*)(v_dst);
  dst->_d = src->_d;
  dst->_h = src->_h;
  dst->_u = src->_u;
  dst->_s = src->_s;
  dst->_cp = src->_cp;
  dst->_cv = src->_cv;
  dst->_pt = src->_pt;
  dst->_pd = src->_pd;
}


#define Modelica_Fluid_Examples_HeatingSystem_heater_flowModel_Medium_ThermodynamicState__desc_added 1
const char* Modelica_Fluid_Examples_HeatingSystem_heater_flowModel_Medium_ThermodynamicState__desc__fields[2] = {"p","T"};
struct record_description Modelica_Fluid_Examples_HeatingSystem_heater_flowModel_Medium_ThermodynamicState__desc = {
  "Modelica_Fluid_Examples_HeatingSystem_heater_flowModel_Medium_ThermodynamicState", /* package_record__X */
  "Modelica.Fluid.Examples.HeatingSystem.heater.flowModel.Medium.ThermodynamicState", /* package.record_X */
  Modelica_Fluid_Examples_HeatingSystem_heater_flowModel_Medium_ThermodynamicState__desc__fields
};

void Modelica_Fluid_Examples_HeatingSystem_heater_flowModel_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths ) {
  Modelica_Fluid_Examples_HeatingSystem_heater_flowModel_Medium_ThermodynamicState* ths = (Modelica_Fluid_Examples_HeatingSystem_heater_flowModel_Medium_ThermodynamicState*)(v_ths);
  // ths->_p has no default value.
  // ths->_T has no default value.
}
void Modelica_Fluid_Examples_HeatingSystem_heater_flowModel_Medium_ThermodynamicState_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_real in_p, modelica_real in_T) {
  Modelica_Fluid_Examples_HeatingSystem_heater_flowModel_Medium_ThermodynamicState* dst = (Modelica_Fluid_Examples_HeatingSystem_heater_flowModel_Medium_ThermodynamicState*)(v_dst);
  dst->_p = in_p;
  dst->_T = in_T;
}

void Modelica_Fluid_Examples_HeatingSystem_heater_flowModel_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst) {
  Modelica_Fluid_Examples_HeatingSystem_heater_flowModel_Medium_ThermodynamicState* src = (Modelica_Fluid_Examples_HeatingSystem_heater_flowModel_Medium_ThermodynamicState*)(v_src);
  Modelica_Fluid_Examples_HeatingSystem_heater_flowModel_Medium_ThermodynamicState* dst = (Modelica_Fluid_Examples_HeatingSystem_heater_flowModel_Medium_ThermodynamicState*)(v_dst);
  dst->_p = src->_p;
  dst->_T = src->_T;
}


#define Modelica_Fluid_Examples_HeatingSystem_heater_heatTransfer_Medium_ThermodynamicState__desc_added 1
const char* Modelica_Fluid_Examples_HeatingSystem_heater_heatTransfer_Medium_ThermodynamicState__desc__fields[2] = {"p","T"};
struct record_description Modelica_Fluid_Examples_HeatingSystem_heater_heatTransfer_Medium_ThermodynamicState__desc = {
  "Modelica_Fluid_Examples_HeatingSystem_heater_heatTransfer_Medium_ThermodynamicState", /* package_record__X */
  "Modelica.Fluid.Examples.HeatingSystem.heater.heatTransfer.Medium.ThermodynamicState", /* package.record_X */
  Modelica_Fluid_Examples_HeatingSystem_heater_heatTransfer_Medium_ThermodynamicState__desc__fields
};

void Modelica_Fluid_Examples_HeatingSystem_heater_heatTransfer_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths ) {
  Modelica_Fluid_Examples_HeatingSystem_heater_heatTransfer_Medium_ThermodynamicState* ths = (Modelica_Fluid_Examples_HeatingSystem_heater_heatTransfer_Medium_ThermodynamicState*)(v_ths);
  // ths->_p has no default value.
  // ths->_T has no default value.
}
void Modelica_Fluid_Examples_HeatingSystem_heater_heatTransfer_Medium_ThermodynamicState_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_real in_p, modelica_real in_T) {
  Modelica_Fluid_Examples_HeatingSystem_heater_heatTransfer_Medium_ThermodynamicState* dst = (Modelica_Fluid_Examples_HeatingSystem_heater_heatTransfer_Medium_ThermodynamicState*)(v_dst);
  dst->_p = in_p;
  dst->_T = in_T;
}

void Modelica_Fluid_Examples_HeatingSystem_heater_heatTransfer_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst) {
  Modelica_Fluid_Examples_HeatingSystem_heater_heatTransfer_Medium_ThermodynamicState* src = (Modelica_Fluid_Examples_HeatingSystem_heater_heatTransfer_Medium_ThermodynamicState*)(v_src);
  Modelica_Fluid_Examples_HeatingSystem_heater_heatTransfer_Medium_ThermodynamicState* dst = (Modelica_Fluid_Examples_HeatingSystem_heater_heatTransfer_Medium_ThermodynamicState*)(v_dst);
  dst->_p = src->_p;
  dst->_T = src->_T;
}


#define Modelica_Fluid_Examples_HeatingSystem_pipe_Medium_ThermodynamicState__desc_added 1
const char* Modelica_Fluid_Examples_HeatingSystem_pipe_Medium_ThermodynamicState__desc__fields[2] = {"p","T"};
struct record_description Modelica_Fluid_Examples_HeatingSystem_pipe_Medium_ThermodynamicState__desc = {
  "Modelica_Fluid_Examples_HeatingSystem_pipe_Medium_ThermodynamicState", /* package_record__X */
  "Modelica.Fluid.Examples.HeatingSystem.pipe.Medium.ThermodynamicState", /* package.record_X */
  Modelica_Fluid_Examples_HeatingSystem_pipe_Medium_ThermodynamicState__desc__fields
};

void Modelica_Fluid_Examples_HeatingSystem_pipe_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths ) {
  Modelica_Fluid_Examples_HeatingSystem_pipe_Medium_ThermodynamicState* ths = (Modelica_Fluid_Examples_HeatingSystem_pipe_Medium_ThermodynamicState*)(v_ths);
  // ths->_p has no default value.
  // ths->_T has no default value.
}
void Modelica_Fluid_Examples_HeatingSystem_pipe_Medium_ThermodynamicState_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_real in_p, modelica_real in_T) {
  Modelica_Fluid_Examples_HeatingSystem_pipe_Medium_ThermodynamicState* dst = (Modelica_Fluid_Examples_HeatingSystem_pipe_Medium_ThermodynamicState*)(v_dst);
  dst->_p = in_p;
  dst->_T = in_T;
}

void Modelica_Fluid_Examples_HeatingSystem_pipe_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst) {
  Modelica_Fluid_Examples_HeatingSystem_pipe_Medium_ThermodynamicState* src = (Modelica_Fluid_Examples_HeatingSystem_pipe_Medium_ThermodynamicState*)(v_src);
  Modelica_Fluid_Examples_HeatingSystem_pipe_Medium_ThermodynamicState* dst = (Modelica_Fluid_Examples_HeatingSystem_pipe_Medium_ThermodynamicState*)(v_dst);
  dst->_p = src->_p;
  dst->_T = src->_T;
}


#define Modelica_Fluid_Examples_HeatingSystem_pipe_flowModel_Medium_ThermodynamicState__desc_added 1
const char* Modelica_Fluid_Examples_HeatingSystem_pipe_flowModel_Medium_ThermodynamicState__desc__fields[2] = {"p","T"};
struct record_description Modelica_Fluid_Examples_HeatingSystem_pipe_flowModel_Medium_ThermodynamicState__desc = {
  "Modelica_Fluid_Examples_HeatingSystem_pipe_flowModel_Medium_ThermodynamicState", /* package_record__X */
  "Modelica.Fluid.Examples.HeatingSystem.pipe.flowModel.Medium.ThermodynamicState", /* package.record_X */
  Modelica_Fluid_Examples_HeatingSystem_pipe_flowModel_Medium_ThermodynamicState__desc__fields
};

void Modelica_Fluid_Examples_HeatingSystem_pipe_flowModel_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths ) {
  Modelica_Fluid_Examples_HeatingSystem_pipe_flowModel_Medium_ThermodynamicState* ths = (Modelica_Fluid_Examples_HeatingSystem_pipe_flowModel_Medium_ThermodynamicState*)(v_ths);
  // ths->_p has no default value.
  // ths->_T has no default value.
}
void Modelica_Fluid_Examples_HeatingSystem_pipe_flowModel_Medium_ThermodynamicState_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_real in_p, modelica_real in_T) {
  Modelica_Fluid_Examples_HeatingSystem_pipe_flowModel_Medium_ThermodynamicState* dst = (Modelica_Fluid_Examples_HeatingSystem_pipe_flowModel_Medium_ThermodynamicState*)(v_dst);
  dst->_p = in_p;
  dst->_T = in_T;
}

void Modelica_Fluid_Examples_HeatingSystem_pipe_flowModel_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst) {
  Modelica_Fluid_Examples_HeatingSystem_pipe_flowModel_Medium_ThermodynamicState* src = (Modelica_Fluid_Examples_HeatingSystem_pipe_flowModel_Medium_ThermodynamicState*)(v_src);
  Modelica_Fluid_Examples_HeatingSystem_pipe_flowModel_Medium_ThermodynamicState* dst = (Modelica_Fluid_Examples_HeatingSystem_pipe_flowModel_Medium_ThermodynamicState*)(v_dst);
  dst->_p = src->_p;
  dst->_T = src->_T;
}


#define Modelica_Fluid_Examples_HeatingSystem_pipe_heatTransfer_Medium_ThermodynamicState__desc_added 1
const char* Modelica_Fluid_Examples_HeatingSystem_pipe_heatTransfer_Medium_ThermodynamicState__desc__fields[2] = {"p","T"};
struct record_description Modelica_Fluid_Examples_HeatingSystem_pipe_heatTransfer_Medium_ThermodynamicState__desc = {
  "Modelica_Fluid_Examples_HeatingSystem_pipe_heatTransfer_Medium_ThermodynamicState", /* package_record__X */
  "Modelica.Fluid.Examples.HeatingSystem.pipe.heatTransfer.Medium.ThermodynamicState", /* package.record_X */
  Modelica_Fluid_Examples_HeatingSystem_pipe_heatTransfer_Medium_ThermodynamicState__desc__fields
};

void Modelica_Fluid_Examples_HeatingSystem_pipe_heatTransfer_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths ) {
  Modelica_Fluid_Examples_HeatingSystem_pipe_heatTransfer_Medium_ThermodynamicState* ths = (Modelica_Fluid_Examples_HeatingSystem_pipe_heatTransfer_Medium_ThermodynamicState*)(v_ths);
  // ths->_p has no default value.
  // ths->_T has no default value.
}
void Modelica_Fluid_Examples_HeatingSystem_pipe_heatTransfer_Medium_ThermodynamicState_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_real in_p, modelica_real in_T) {
  Modelica_Fluid_Examples_HeatingSystem_pipe_heatTransfer_Medium_ThermodynamicState* dst = (Modelica_Fluid_Examples_HeatingSystem_pipe_heatTransfer_Medium_ThermodynamicState*)(v_dst);
  dst->_p = in_p;
  dst->_T = in_T;
}

void Modelica_Fluid_Examples_HeatingSystem_pipe_heatTransfer_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst) {
  Modelica_Fluid_Examples_HeatingSystem_pipe_heatTransfer_Medium_ThermodynamicState* src = (Modelica_Fluid_Examples_HeatingSystem_pipe_heatTransfer_Medium_ThermodynamicState*)(v_src);
  Modelica_Fluid_Examples_HeatingSystem_pipe_heatTransfer_Medium_ThermodynamicState* dst = (Modelica_Fluid_Examples_HeatingSystem_pipe_heatTransfer_Medium_ThermodynamicState*)(v_dst);
  dst->_p = src->_p;
  dst->_T = src->_T;
}


#define Modelica_Fluid_Examples_HeatingSystem_pump_Medium_ThermodynamicState__desc_added 1
const char* Modelica_Fluid_Examples_HeatingSystem_pump_Medium_ThermodynamicState__desc__fields[2] = {"p","T"};
struct record_description Modelica_Fluid_Examples_HeatingSystem_pump_Medium_ThermodynamicState__desc = {
  "Modelica_Fluid_Examples_HeatingSystem_pump_Medium_ThermodynamicState", /* package_record__X */
  "Modelica.Fluid.Examples.HeatingSystem.pump.Medium.ThermodynamicState", /* package.record_X */
  Modelica_Fluid_Examples_HeatingSystem_pump_Medium_ThermodynamicState__desc__fields
};

void Modelica_Fluid_Examples_HeatingSystem_pump_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths ) {
  Modelica_Fluid_Examples_HeatingSystem_pump_Medium_ThermodynamicState* ths = (Modelica_Fluid_Examples_HeatingSystem_pump_Medium_ThermodynamicState*)(v_ths);
  // ths->_p has no default value.
  // ths->_T has no default value.
}
void Modelica_Fluid_Examples_HeatingSystem_pump_Medium_ThermodynamicState_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_real in_p, modelica_real in_T) {
  Modelica_Fluid_Examples_HeatingSystem_pump_Medium_ThermodynamicState* dst = (Modelica_Fluid_Examples_HeatingSystem_pump_Medium_ThermodynamicState*)(v_dst);
  dst->_p = in_p;
  dst->_T = in_T;
}

void Modelica_Fluid_Examples_HeatingSystem_pump_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst) {
  Modelica_Fluid_Examples_HeatingSystem_pump_Medium_ThermodynamicState* src = (Modelica_Fluid_Examples_HeatingSystem_pump_Medium_ThermodynamicState*)(v_src);
  Modelica_Fluid_Examples_HeatingSystem_pump_Medium_ThermodynamicState* dst = (Modelica_Fluid_Examples_HeatingSystem_pump_Medium_ThermodynamicState*)(v_dst);
  dst->_p = src->_p;
  dst->_T = src->_T;
}


#define Modelica_Fluid_Examples_HeatingSystem_pump_heatTransfer_Medium_ThermodynamicState__desc_added 1
const char* Modelica_Fluid_Examples_HeatingSystem_pump_heatTransfer_Medium_ThermodynamicState__desc__fields[2] = {"p","T"};
struct record_description Modelica_Fluid_Examples_HeatingSystem_pump_heatTransfer_Medium_ThermodynamicState__desc = {
  "Modelica_Fluid_Examples_HeatingSystem_pump_heatTransfer_Medium_ThermodynamicState", /* package_record__X */
  "Modelica.Fluid.Examples.HeatingSystem.pump.heatTransfer.Medium.ThermodynamicState", /* package.record_X */
  Modelica_Fluid_Examples_HeatingSystem_pump_heatTransfer_Medium_ThermodynamicState__desc__fields
};

void Modelica_Fluid_Examples_HeatingSystem_pump_heatTransfer_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths ) {
  Modelica_Fluid_Examples_HeatingSystem_pump_heatTransfer_Medium_ThermodynamicState* ths = (Modelica_Fluid_Examples_HeatingSystem_pump_heatTransfer_Medium_ThermodynamicState*)(v_ths);
  // ths->_p has no default value.
  // ths->_T has no default value.
}
void Modelica_Fluid_Examples_HeatingSystem_pump_heatTransfer_Medium_ThermodynamicState_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_real in_p, modelica_real in_T) {
  Modelica_Fluid_Examples_HeatingSystem_pump_heatTransfer_Medium_ThermodynamicState* dst = (Modelica_Fluid_Examples_HeatingSystem_pump_heatTransfer_Medium_ThermodynamicState*)(v_dst);
  dst->_p = in_p;
  dst->_T = in_T;
}

void Modelica_Fluid_Examples_HeatingSystem_pump_heatTransfer_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst) {
  Modelica_Fluid_Examples_HeatingSystem_pump_heatTransfer_Medium_ThermodynamicState* src = (Modelica_Fluid_Examples_HeatingSystem_pump_heatTransfer_Medium_ThermodynamicState*)(v_src);
  Modelica_Fluid_Examples_HeatingSystem_pump_heatTransfer_Medium_ThermodynamicState* dst = (Modelica_Fluid_Examples_HeatingSystem_pump_heatTransfer_Medium_ThermodynamicState*)(v_dst);
  dst->_p = src->_p;
  dst->_T = src->_T;
}


#define Modelica_Fluid_Examples_HeatingSystem_pump_monitoring_Medium_ThermodynamicState__desc_added 1
const char* Modelica_Fluid_Examples_HeatingSystem_pump_monitoring_Medium_ThermodynamicState__desc__fields[2] = {"p","T"};
struct record_description Modelica_Fluid_Examples_HeatingSystem_pump_monitoring_Medium_ThermodynamicState__desc = {
  "Modelica_Fluid_Examples_HeatingSystem_pump_monitoring_Medium_ThermodynamicState", /* package_record__X */
  "Modelica.Fluid.Examples.HeatingSystem.pump.monitoring.Medium.ThermodynamicState", /* package.record_X */
  Modelica_Fluid_Examples_HeatingSystem_pump_monitoring_Medium_ThermodynamicState__desc__fields
};

void Modelica_Fluid_Examples_HeatingSystem_pump_monitoring_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths ) {
  Modelica_Fluid_Examples_HeatingSystem_pump_monitoring_Medium_ThermodynamicState* ths = (Modelica_Fluid_Examples_HeatingSystem_pump_monitoring_Medium_ThermodynamicState*)(v_ths);
  // ths->_p has no default value.
  // ths->_T has no default value.
}
void Modelica_Fluid_Examples_HeatingSystem_pump_monitoring_Medium_ThermodynamicState_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_real in_p, modelica_real in_T) {
  Modelica_Fluid_Examples_HeatingSystem_pump_monitoring_Medium_ThermodynamicState* dst = (Modelica_Fluid_Examples_HeatingSystem_pump_monitoring_Medium_ThermodynamicState*)(v_dst);
  dst->_p = in_p;
  dst->_T = in_T;
}

void Modelica_Fluid_Examples_HeatingSystem_pump_monitoring_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst) {
  Modelica_Fluid_Examples_HeatingSystem_pump_monitoring_Medium_ThermodynamicState* src = (Modelica_Fluid_Examples_HeatingSystem_pump_monitoring_Medium_ThermodynamicState*)(v_src);
  Modelica_Fluid_Examples_HeatingSystem_pump_monitoring_Medium_ThermodynamicState* dst = (Modelica_Fluid_Examples_HeatingSystem_pump_monitoring_Medium_ThermodynamicState*)(v_dst);
  dst->_p = src->_p;
  dst->_T = src->_T;
}


#define Modelica_Fluid_Examples_HeatingSystem_radiator_Medium_ThermodynamicState__desc_added 1
const char* Modelica_Fluid_Examples_HeatingSystem_radiator_Medium_ThermodynamicState__desc__fields[2] = {"p","T"};
struct record_description Modelica_Fluid_Examples_HeatingSystem_radiator_Medium_ThermodynamicState__desc = {
  "Modelica_Fluid_Examples_HeatingSystem_radiator_Medium_ThermodynamicState", /* package_record__X */
  "Modelica.Fluid.Examples.HeatingSystem.radiator.Medium.ThermodynamicState", /* package.record_X */
  Modelica_Fluid_Examples_HeatingSystem_radiator_Medium_ThermodynamicState__desc__fields
};

void Modelica_Fluid_Examples_HeatingSystem_radiator_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths ) {
  Modelica_Fluid_Examples_HeatingSystem_radiator_Medium_ThermodynamicState* ths = (Modelica_Fluid_Examples_HeatingSystem_radiator_Medium_ThermodynamicState*)(v_ths);
  // ths->_p has no default value.
  // ths->_T has no default value.
}
void Modelica_Fluid_Examples_HeatingSystem_radiator_Medium_ThermodynamicState_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_real in_p, modelica_real in_T) {
  Modelica_Fluid_Examples_HeatingSystem_radiator_Medium_ThermodynamicState* dst = (Modelica_Fluid_Examples_HeatingSystem_radiator_Medium_ThermodynamicState*)(v_dst);
  dst->_p = in_p;
  dst->_T = in_T;
}

void Modelica_Fluid_Examples_HeatingSystem_radiator_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst) {
  Modelica_Fluid_Examples_HeatingSystem_radiator_Medium_ThermodynamicState* src = (Modelica_Fluid_Examples_HeatingSystem_radiator_Medium_ThermodynamicState*)(v_src);
  Modelica_Fluid_Examples_HeatingSystem_radiator_Medium_ThermodynamicState* dst = (Modelica_Fluid_Examples_HeatingSystem_radiator_Medium_ThermodynamicState*)(v_dst);
  dst->_p = src->_p;
  dst->_T = src->_T;
}


#define Modelica_Fluid_Examples_HeatingSystem_radiator_flowModel_Medium_ThermodynamicState__desc_added 1
const char* Modelica_Fluid_Examples_HeatingSystem_radiator_flowModel_Medium_ThermodynamicState__desc__fields[2] = {"p","T"};
struct record_description Modelica_Fluid_Examples_HeatingSystem_radiator_flowModel_Medium_ThermodynamicState__desc = {
  "Modelica_Fluid_Examples_HeatingSystem_radiator_flowModel_Medium_ThermodynamicState", /* package_record__X */
  "Modelica.Fluid.Examples.HeatingSystem.radiator.flowModel.Medium.ThermodynamicState", /* package.record_X */
  Modelica_Fluid_Examples_HeatingSystem_radiator_flowModel_Medium_ThermodynamicState__desc__fields
};

void Modelica_Fluid_Examples_HeatingSystem_radiator_flowModel_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths ) {
  Modelica_Fluid_Examples_HeatingSystem_radiator_flowModel_Medium_ThermodynamicState* ths = (Modelica_Fluid_Examples_HeatingSystem_radiator_flowModel_Medium_ThermodynamicState*)(v_ths);
  // ths->_p has no default value.
  // ths->_T has no default value.
}
void Modelica_Fluid_Examples_HeatingSystem_radiator_flowModel_Medium_ThermodynamicState_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_real in_p, modelica_real in_T) {
  Modelica_Fluid_Examples_HeatingSystem_radiator_flowModel_Medium_ThermodynamicState* dst = (Modelica_Fluid_Examples_HeatingSystem_radiator_flowModel_Medium_ThermodynamicState*)(v_dst);
  dst->_p = in_p;
  dst->_T = in_T;
}

void Modelica_Fluid_Examples_HeatingSystem_radiator_flowModel_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst) {
  Modelica_Fluid_Examples_HeatingSystem_radiator_flowModel_Medium_ThermodynamicState* src = (Modelica_Fluid_Examples_HeatingSystem_radiator_flowModel_Medium_ThermodynamicState*)(v_src);
  Modelica_Fluid_Examples_HeatingSystem_radiator_flowModel_Medium_ThermodynamicState* dst = (Modelica_Fluid_Examples_HeatingSystem_radiator_flowModel_Medium_ThermodynamicState*)(v_dst);
  dst->_p = src->_p;
  dst->_T = src->_T;
}


#define Modelica_Fluid_Examples_HeatingSystem_radiator_heatTransfer_Medium_ThermodynamicState__desc_added 1
const char* Modelica_Fluid_Examples_HeatingSystem_radiator_heatTransfer_Medium_ThermodynamicState__desc__fields[2] = {"p","T"};
struct record_description Modelica_Fluid_Examples_HeatingSystem_radiator_heatTransfer_Medium_ThermodynamicState__desc = {
  "Modelica_Fluid_Examples_HeatingSystem_radiator_heatTransfer_Medium_ThermodynamicState", /* package_record__X */
  "Modelica.Fluid.Examples.HeatingSystem.radiator.heatTransfer.Medium.ThermodynamicState", /* package.record_X */
  Modelica_Fluid_Examples_HeatingSystem_radiator_heatTransfer_Medium_ThermodynamicState__desc__fields
};

void Modelica_Fluid_Examples_HeatingSystem_radiator_heatTransfer_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths ) {
  Modelica_Fluid_Examples_HeatingSystem_radiator_heatTransfer_Medium_ThermodynamicState* ths = (Modelica_Fluid_Examples_HeatingSystem_radiator_heatTransfer_Medium_ThermodynamicState*)(v_ths);
  // ths->_p has no default value.
  // ths->_T has no default value.
}
void Modelica_Fluid_Examples_HeatingSystem_radiator_heatTransfer_Medium_ThermodynamicState_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_real in_p, modelica_real in_T) {
  Modelica_Fluid_Examples_HeatingSystem_radiator_heatTransfer_Medium_ThermodynamicState* dst = (Modelica_Fluid_Examples_HeatingSystem_radiator_heatTransfer_Medium_ThermodynamicState*)(v_dst);
  dst->_p = in_p;
  dst->_T = in_T;
}

void Modelica_Fluid_Examples_HeatingSystem_radiator_heatTransfer_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst) {
  Modelica_Fluid_Examples_HeatingSystem_radiator_heatTransfer_Medium_ThermodynamicState* src = (Modelica_Fluid_Examples_HeatingSystem_radiator_heatTransfer_Medium_ThermodynamicState*)(v_src);
  Modelica_Fluid_Examples_HeatingSystem_radiator_heatTransfer_Medium_ThermodynamicState* dst = (Modelica_Fluid_Examples_HeatingSystem_radiator_heatTransfer_Medium_ThermodynamicState*)(v_dst);
  dst->_p = src->_p;
  dst->_T = src->_T;
}


#define Modelica_Fluid_Examples_HeatingSystem_sensor__T__forward_Medium_ThermodynamicState__desc_added 1
const char* Modelica_Fluid_Examples_HeatingSystem_sensor__T__forward_Medium_ThermodynamicState__desc__fields[2] = {"p","T"};
struct record_description Modelica_Fluid_Examples_HeatingSystem_sensor__T__forward_Medium_ThermodynamicState__desc = {
  "Modelica_Fluid_Examples_HeatingSystem_sensor__T__forward_Medium_ThermodynamicState", /* package_record__X */
  "Modelica.Fluid.Examples.HeatingSystem.sensor_T_forward.Medium.ThermodynamicState", /* package.record_X */
  Modelica_Fluid_Examples_HeatingSystem_sensor__T__forward_Medium_ThermodynamicState__desc__fields
};

void Modelica_Fluid_Examples_HeatingSystem_sensor__T__forward_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths ) {
  Modelica_Fluid_Examples_HeatingSystem_sensor__T__forward_Medium_ThermodynamicState* ths = (Modelica_Fluid_Examples_HeatingSystem_sensor__T__forward_Medium_ThermodynamicState*)(v_ths);
  // ths->_p has no default value.
  // ths->_T has no default value.
}
void Modelica_Fluid_Examples_HeatingSystem_sensor__T__forward_Medium_ThermodynamicState_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_real in_p, modelica_real in_T) {
  Modelica_Fluid_Examples_HeatingSystem_sensor__T__forward_Medium_ThermodynamicState* dst = (Modelica_Fluid_Examples_HeatingSystem_sensor__T__forward_Medium_ThermodynamicState*)(v_dst);
  dst->_p = in_p;
  dst->_T = in_T;
}

void Modelica_Fluid_Examples_HeatingSystem_sensor__T__forward_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst) {
  Modelica_Fluid_Examples_HeatingSystem_sensor__T__forward_Medium_ThermodynamicState* src = (Modelica_Fluid_Examples_HeatingSystem_sensor__T__forward_Medium_ThermodynamicState*)(v_src);
  Modelica_Fluid_Examples_HeatingSystem_sensor__T__forward_Medium_ThermodynamicState* dst = (Modelica_Fluid_Examples_HeatingSystem_sensor__T__forward_Medium_ThermodynamicState*)(v_dst);
  dst->_p = src->_p;
  dst->_T = src->_T;
}


#define Modelica_Fluid_Examples_HeatingSystem_sensor__T__return_Medium_ThermodynamicState__desc_added 1
const char* Modelica_Fluid_Examples_HeatingSystem_sensor__T__return_Medium_ThermodynamicState__desc__fields[2] = {"p","T"};
struct record_description Modelica_Fluid_Examples_HeatingSystem_sensor__T__return_Medium_ThermodynamicState__desc = {
  "Modelica_Fluid_Examples_HeatingSystem_sensor__T__return_Medium_ThermodynamicState", /* package_record__X */
  "Modelica.Fluid.Examples.HeatingSystem.sensor_T_return.Medium.ThermodynamicState", /* package.record_X */
  Modelica_Fluid_Examples_HeatingSystem_sensor__T__return_Medium_ThermodynamicState__desc__fields
};

void Modelica_Fluid_Examples_HeatingSystem_sensor__T__return_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths ) {
  Modelica_Fluid_Examples_HeatingSystem_sensor__T__return_Medium_ThermodynamicState* ths = (Modelica_Fluid_Examples_HeatingSystem_sensor__T__return_Medium_ThermodynamicState*)(v_ths);
  // ths->_p has no default value.
  // ths->_T has no default value.
}
void Modelica_Fluid_Examples_HeatingSystem_sensor__T__return_Medium_ThermodynamicState_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_real in_p, modelica_real in_T) {
  Modelica_Fluid_Examples_HeatingSystem_sensor__T__return_Medium_ThermodynamicState* dst = (Modelica_Fluid_Examples_HeatingSystem_sensor__T__return_Medium_ThermodynamicState*)(v_dst);
  dst->_p = in_p;
  dst->_T = in_T;
}

void Modelica_Fluid_Examples_HeatingSystem_sensor__T__return_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst) {
  Modelica_Fluid_Examples_HeatingSystem_sensor__T__return_Medium_ThermodynamicState* src = (Modelica_Fluid_Examples_HeatingSystem_sensor__T__return_Medium_ThermodynamicState*)(v_src);
  Modelica_Fluid_Examples_HeatingSystem_sensor__T__return_Medium_ThermodynamicState* dst = (Modelica_Fluid_Examples_HeatingSystem_sensor__T__return_Medium_ThermodynamicState*)(v_dst);
  dst->_p = src->_p;
  dst->_T = src->_T;
}


#define Modelica_Fluid_Examples_HeatingSystem_valve_Medium_ThermodynamicState__desc_added 1
const char* Modelica_Fluid_Examples_HeatingSystem_valve_Medium_ThermodynamicState__desc__fields[2] = {"p","T"};
struct record_description Modelica_Fluid_Examples_HeatingSystem_valve_Medium_ThermodynamicState__desc = {
  "Modelica_Fluid_Examples_HeatingSystem_valve_Medium_ThermodynamicState", /* package_record__X */
  "Modelica.Fluid.Examples.HeatingSystem.valve.Medium.ThermodynamicState", /* package.record_X */
  Modelica_Fluid_Examples_HeatingSystem_valve_Medium_ThermodynamicState__desc__fields
};

void Modelica_Fluid_Examples_HeatingSystem_valve_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths ) {
  Modelica_Fluid_Examples_HeatingSystem_valve_Medium_ThermodynamicState* ths = (Modelica_Fluid_Examples_HeatingSystem_valve_Medium_ThermodynamicState*)(v_ths);
  // ths->_p has no default value.
  // ths->_T has no default value.
}
void Modelica_Fluid_Examples_HeatingSystem_valve_Medium_ThermodynamicState_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_real in_p, modelica_real in_T) {
  Modelica_Fluid_Examples_HeatingSystem_valve_Medium_ThermodynamicState* dst = (Modelica_Fluid_Examples_HeatingSystem_valve_Medium_ThermodynamicState*)(v_dst);
  dst->_p = in_p;
  dst->_T = in_T;
}

void Modelica_Fluid_Examples_HeatingSystem_valve_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst) {
  Modelica_Fluid_Examples_HeatingSystem_valve_Medium_ThermodynamicState* src = (Modelica_Fluid_Examples_HeatingSystem_valve_Medium_ThermodynamicState*)(v_src);
  Modelica_Fluid_Examples_HeatingSystem_valve_Medium_ThermodynamicState* dst = (Modelica_Fluid_Examples_HeatingSystem_valve_Medium_ThermodynamicState*)(v_dst);
  dst->_p = src->_p;
  dst->_T = src->_T;
}


#define Modelica_Fluid_Examples_HeatingSystem_tank_heatTransfer_Medium_ThermodynamicState__desc_added 1
const char* Modelica_Fluid_Examples_HeatingSystem_tank_heatTransfer_Medium_ThermodynamicState__desc__fields[5] = {"phase","h","d","T","p"};
struct record_description Modelica_Fluid_Examples_HeatingSystem_tank_heatTransfer_Medium_ThermodynamicState__desc = {
  "Modelica_Fluid_Examples_HeatingSystem_tank_heatTransfer_Medium_ThermodynamicState", /* package_record__X */
  "Modelica.Fluid.Examples.HeatingSystem.tank.heatTransfer.Medium.ThermodynamicState", /* package.record_X */
  Modelica_Fluid_Examples_HeatingSystem_tank_heatTransfer_Medium_ThermodynamicState__desc__fields
};

void Modelica_Fluid_Examples_HeatingSystem_tank_heatTransfer_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths ) {
  Modelica_Fluid_Examples_HeatingSystem_tank_heatTransfer_Medium_ThermodynamicState* ths = (Modelica_Fluid_Examples_HeatingSystem_tank_heatTransfer_Medium_ThermodynamicState*)(v_ths);
  // ths->_phase has no default value.
  // ths->_h has no default value.
  // ths->_d has no default value.
  // ths->_T has no default value.
  // ths->_p has no default value.
}
void Modelica_Fluid_Examples_HeatingSystem_tank_heatTransfer_Medium_ThermodynamicState_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_integer in_phase, modelica_real in_h, modelica_real in_d, modelica_real in_T, modelica_real in_p) {
  Modelica_Fluid_Examples_HeatingSystem_tank_heatTransfer_Medium_ThermodynamicState* dst = (Modelica_Fluid_Examples_HeatingSystem_tank_heatTransfer_Medium_ThermodynamicState*)(v_dst);
  dst->_phase = in_phase;
  dst->_h = in_h;
  dst->_d = in_d;
  dst->_T = in_T;
  dst->_p = in_p;
}

void Modelica_Fluid_Examples_HeatingSystem_tank_heatTransfer_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst) {
  Modelica_Fluid_Examples_HeatingSystem_tank_heatTransfer_Medium_ThermodynamicState* src = (Modelica_Fluid_Examples_HeatingSystem_tank_heatTransfer_Medium_ThermodynamicState*)(v_src);
  Modelica_Fluid_Examples_HeatingSystem_tank_heatTransfer_Medium_ThermodynamicState* dst = (Modelica_Fluid_Examples_HeatingSystem_tank_heatTransfer_Medium_ThermodynamicState*)(v_dst);
  dst->_phase = src->_phase;
  dst->_h = src->_h;
  dst->_d = src->_d;
  dst->_T = src->_T;
  dst->_p = src->_p;
}

#ifdef __cplusplus
}
#endif

